apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yaml: |
    scrape_configs:
    - job_name: 'cloudprober'
      scrape_interval: 10s
      static_configs:
        - targets: ['localhost:9313']
