apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-probe-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-probe-prometheus
  template:
    metadata:
      labels:
        app: net-probe-prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        args: [
          "--config.file","/cfg/prometheus.yaml",
        ]
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /cfg
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  name: net-probe-prometheus
  labels:
    app: net-probe-prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: net-probe-prometheus
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yaml: |
    scrape_configs:
    - job_name: 'cloudprober'
      scrape_interval: 15s
      static_configs:
        - targets: ['10.64.3.23:9313','10.128.0.4:9313']
