apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-probe
  template:
    metadata:
      labels:
        app: net-probe
    spec:
      containers:
      - name: cloudprober
        image: cloudprober/cloudprober
        args: [
          "--config_file","/cfg/cloudprober.cfg",
          "--logtostderr"
        ]
        ports:
        - name: http
          containerPort: 9313
        volumeMounts:
        - name: cloudprober-config
          mountPath: /cfg
        # env:
        # - name: CLOUDPROBER_PORT
        #   value: "9313"
      volumes:
      - name: cloudprober-config
        configMap:
          name: cloudprober-config
---
apiVersion: v1
kind: Service
metadata:
  name: net-probe
  labels:
    app: net-probe
spec:
  ports:
  - port: 9313
    protocol: TCP
    targetPort: 9313
  selector:
    app: net-probe
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudprober-config
  namespace: default
data:
  cloudprober.cfg: |
    probe {
      name: "nodes"
      type: HTTP
      targets {
        host_names: "10.128.0.3,10.128.0.4,10.128.0.5"
      }
      interval_msec: 15000
      timeout_msec: 1000
    }
    probe {
      name: "pods"
      type: HTTP
      targets {
        host_names: "10.64.1.9,10.64.2.13,10.64.3.16"
      }
      interval_msec: 15000
      timeout_msec: 1000
    }
    probe {
      name: "services"
      type: HTTP
      targets {
        host_names: "10.0.6.201,10.0.143.250,my-nginx,my-nginx-hostnetwork"
      }
      interval_msec: 15000
      timeout_msec: 1000
    }
    probe {
      name: "external"
      type: HTTP
      targets {
        host_names: "www.google.com"
      }
      interval_msec: 15000
      timeout_msec: 1000
    }
    surfacer {
      type: PROMETHEUS 
    }
    surfacer {
      type: STACKDRIVER
    }
    surfacer {
      type: FILE 
      # file_surfacer {
      #   file_path: "/home/cloudprober.log"
      # }
    }
    sysvars_interval_msec: 3600000
